global using sparcity_pattern = pagmo.SWIGTYPE_p_std__vectorT_std__pairT_size_t_size_t_t_t;
global using individuals_group_t = pagmo.SWIGTYPE_p_std__tupleT_std__vectorT_unsigned_long_long_t_std__vectorT_std__vectorT_double_t_t_std__vectorT_std__vectorT_double_t_t_t;

