//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public class IpoptLogEntryVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<IpoptLogEntry>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IpoptLogEntryVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IpoptLogEntryVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IpoptLogEntryVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IpoptLogEntryVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pagmoPINVOKE.delete_IpoptLogEntryVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IpoptLogEntryVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (IpoptLogEntry element in c) {
      this.Add(element);
    }
  }

  public IpoptLogEntryVector(global::System.Collections.Generic.IEnumerable<IpoptLogEntry> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (IpoptLogEntry element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public IpoptLogEntry this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(IpoptLogEntry[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(IpoptLogEntry[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, IpoptLogEntry[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public IpoptLogEntry[] ToArray() {
    IpoptLogEntry[] array = new IpoptLogEntry[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<IpoptLogEntry> global::System.Collections.Generic.IEnumerable<IpoptLogEntry>.GetEnumerator() {
    return new IpoptLogEntryVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new IpoptLogEntryVectorEnumerator(this);
  }

  public IpoptLogEntryVectorEnumerator GetEnumerator() {
    return new IpoptLogEntryVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class IpoptLogEntryVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<IpoptLogEntry>
  {
    private IpoptLogEntryVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public IpoptLogEntryVectorEnumerator(IpoptLogEntryVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public IpoptLogEntry Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (IpoptLogEntry)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public IpoptLogEntryVector() : this(pagmoPINVOKE.new_IpoptLogEntryVector__SWIG_0(), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public IpoptLogEntryVector(IpoptLogEntryVector other) : this(pagmoPINVOKE.new_IpoptLogEntryVector__SWIG_1(IpoptLogEntryVector.getCPtr(other)), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    pagmoPINVOKE.IpoptLogEntryVector_Clear(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(IpoptLogEntry x) {
    pagmoPINVOKE.IpoptLogEntryVector_Add(swigCPtr, IpoptLogEntry.getCPtr(x));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = pagmoPINVOKE.IpoptLogEntryVector_size(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool empty() {
    bool ret = pagmoPINVOKE.IpoptLogEntryVector_empty(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = pagmoPINVOKE.IpoptLogEntryVector_capacity(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    pagmoPINVOKE.IpoptLogEntryVector_reserve(swigCPtr, n);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public IpoptLogEntryVector(int capacity) : this(pagmoPINVOKE.new_IpoptLogEntryVector__SWIG_2(capacity), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  private IpoptLogEntry getitemcopy(int index) {
    IpoptLogEntry ret = new IpoptLogEntry(pagmoPINVOKE.IpoptLogEntryVector_getitemcopy(swigCPtr, index), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private IpoptLogEntry getitem(int index) {
    IpoptLogEntry ret = new IpoptLogEntry(pagmoPINVOKE.IpoptLogEntryVector_getitem(swigCPtr, index), false);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, IpoptLogEntry val) {
    pagmoPINVOKE.IpoptLogEntryVector_setitem(swigCPtr, index, IpoptLogEntry.getCPtr(val));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(IpoptLogEntryVector values) {
    pagmoPINVOKE.IpoptLogEntryVector_AddRange(swigCPtr, IpoptLogEntryVector.getCPtr(values));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public IpoptLogEntryVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = pagmoPINVOKE.IpoptLogEntryVector_GetRange(swigCPtr, index, count);
    IpoptLogEntryVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new IpoptLogEntryVector(cPtr, true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, IpoptLogEntry x) {
    pagmoPINVOKE.IpoptLogEntryVector_Insert(swigCPtr, index, IpoptLogEntry.getCPtr(x));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, IpoptLogEntryVector values) {
    pagmoPINVOKE.IpoptLogEntryVector_InsertRange(swigCPtr, index, IpoptLogEntryVector.getCPtr(values));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    pagmoPINVOKE.IpoptLogEntryVector_RemoveAt(swigCPtr, index);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    pagmoPINVOKE.IpoptLogEntryVector_RemoveRange(swigCPtr, index, count);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static IpoptLogEntryVector Repeat(IpoptLogEntry value, int count) {
    global::System.IntPtr cPtr = pagmoPINVOKE.IpoptLogEntryVector_Repeat(IpoptLogEntry.getCPtr(value), count);
    IpoptLogEntryVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new IpoptLogEntryVector(cPtr, true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    pagmoPINVOKE.IpoptLogEntryVector_Reverse__SWIG_0(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    pagmoPINVOKE.IpoptLogEntryVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, IpoptLogEntryVector values) {
    pagmoPINVOKE.IpoptLogEntryVector_SetRange(swigCPtr, index, IpoptLogEntryVector.getCPtr(values));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
