//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public class CstrsLogEntryVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<CstrsLogEntry>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CstrsLogEntryVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CstrsLogEntryVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CstrsLogEntryVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CstrsLogEntryVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pagmoPINVOKE.delete_CstrsLogEntryVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CstrsLogEntryVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CstrsLogEntry element in c) {
      this.Add(element);
    }
  }

  public CstrsLogEntryVector(global::System.Collections.Generic.IEnumerable<CstrsLogEntry> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CstrsLogEntry element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public CstrsLogEntry this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(CstrsLogEntry[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(CstrsLogEntry[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, CstrsLogEntry[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public CstrsLogEntry[] ToArray() {
    CstrsLogEntry[] array = new CstrsLogEntry[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<CstrsLogEntry> global::System.Collections.Generic.IEnumerable<CstrsLogEntry>.GetEnumerator() {
    return new CstrsLogEntryVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new CstrsLogEntryVectorEnumerator(this);
  }

  public CstrsLogEntryVectorEnumerator GetEnumerator() {
    return new CstrsLogEntryVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CstrsLogEntryVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<CstrsLogEntry>
  {
    private CstrsLogEntryVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CstrsLogEntryVectorEnumerator(CstrsLogEntryVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public CstrsLogEntry Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (CstrsLogEntry)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public CstrsLogEntryVector() : this(pagmoPINVOKE.new_CstrsLogEntryVector__SWIG_0(), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public CstrsLogEntryVector(CstrsLogEntryVector other) : this(pagmoPINVOKE.new_CstrsLogEntryVector__SWIG_1(CstrsLogEntryVector.getCPtr(other)), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    pagmoPINVOKE.CstrsLogEntryVector_Clear(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(CstrsLogEntry x) {
    pagmoPINVOKE.CstrsLogEntryVector_Add(swigCPtr, CstrsLogEntry.getCPtr(x));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = pagmoPINVOKE.CstrsLogEntryVector_size(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool empty() {
    bool ret = pagmoPINVOKE.CstrsLogEntryVector_empty(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = pagmoPINVOKE.CstrsLogEntryVector_capacity(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    pagmoPINVOKE.CstrsLogEntryVector_reserve(swigCPtr, n);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public CstrsLogEntryVector(int capacity) : this(pagmoPINVOKE.new_CstrsLogEntryVector__SWIG_2(capacity), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  private CstrsLogEntry getitemcopy(int index) {
    CstrsLogEntry ret = new CstrsLogEntry(pagmoPINVOKE.CstrsLogEntryVector_getitemcopy(swigCPtr, index), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private CstrsLogEntry getitem(int index) {
    CstrsLogEntry ret = new CstrsLogEntry(pagmoPINVOKE.CstrsLogEntryVector_getitem(swigCPtr, index), false);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, CstrsLogEntry val) {
    pagmoPINVOKE.CstrsLogEntryVector_setitem(swigCPtr, index, CstrsLogEntry.getCPtr(val));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CstrsLogEntryVector values) {
    pagmoPINVOKE.CstrsLogEntryVector_AddRange(swigCPtr, CstrsLogEntryVector.getCPtr(values));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public CstrsLogEntryVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = pagmoPINVOKE.CstrsLogEntryVector_GetRange(swigCPtr, index, count);
    CstrsLogEntryVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new CstrsLogEntryVector(cPtr, true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, CstrsLogEntry x) {
    pagmoPINVOKE.CstrsLogEntryVector_Insert(swigCPtr, index, CstrsLogEntry.getCPtr(x));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CstrsLogEntryVector values) {
    pagmoPINVOKE.CstrsLogEntryVector_InsertRange(swigCPtr, index, CstrsLogEntryVector.getCPtr(values));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    pagmoPINVOKE.CstrsLogEntryVector_RemoveAt(swigCPtr, index);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    pagmoPINVOKE.CstrsLogEntryVector_RemoveRange(swigCPtr, index, count);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CstrsLogEntryVector Repeat(CstrsLogEntry value, int count) {
    global::System.IntPtr cPtr = pagmoPINVOKE.CstrsLogEntryVector_Repeat(CstrsLogEntry.getCPtr(value), count);
    CstrsLogEntryVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new CstrsLogEntryVector(cPtr, true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    pagmoPINVOKE.CstrsLogEntryVector_Reverse__SWIG_0(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    pagmoPINVOKE.CstrsLogEntryVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CstrsLogEntryVector values) {
    pagmoPINVOKE.CstrsLogEntryVector_SetRange(swigCPtr, index, CstrsLogEntryVector.getCPtr(values));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
