//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public class DeLogEntry : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DeLogEntry(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DeLogEntry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DeLogEntry obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DeLogEntry() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pagmoPINVOKE.delete_DeLogEntry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint gen {
    set {
      pagmoPINVOKE.DeLogEntry_gen_set(swigCPtr, value);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = pagmoPINVOKE.DeLogEntry_gen_get(swigCPtr);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ulong fevals {
    set {
      pagmoPINVOKE.DeLogEntry_fevals_set(swigCPtr, value);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ulong ret = pagmoPINVOKE.DeLogEntry_fevals_get(swigCPtr);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double best {
    set {
      pagmoPINVOKE.DeLogEntry_best_set(swigCPtr, value);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = pagmoPINVOKE.DeLogEntry_best_get(swigCPtr);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double feval_difference {
    set {
      pagmoPINVOKE.DeLogEntry_feval_difference_set(swigCPtr, value);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = pagmoPINVOKE.DeLogEntry_feval_difference_get(swigCPtr);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double dx {
    set {
      pagmoPINVOKE.DeLogEntry_dx_set(swigCPtr, value);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = pagmoPINVOKE.DeLogEntry_dx_get(swigCPtr);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public DeLogEntry() : this(pagmoPINVOKE.new_DeLogEntry__SWIG_0(), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public DeLogEntry(uint gen_, ulong fevals_, double best_, double feval_difference_, double dx_) : this(pagmoPINVOKE.new_DeLogEntry__SWIG_1(gen_, fevals_, best_, feval_difference_, dx_), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
