//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public partial class inventory : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal inventory(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(inventory obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(inventory obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~inventory() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pagmoPINVOKE.delete_inventory(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public inventory(uint weeks, uint sample_size, uint seed) : this(pagmoPINVOKE.new_inventory__SWIG_0(weeks, sample_size, seed), true) {
  }

  public inventory(uint weeks, uint sample_size) : this(pagmoPINVOKE.new_inventory__SWIG_1(weeks, sample_size), true) {
  }

  public inventory(uint weeks) : this(pagmoPINVOKE.new_inventory__SWIG_2(weeks), true) {
  }

  public inventory() : this(pagmoPINVOKE.new_inventory__SWIG_3(), true) {
  }

  public DoubleVector fitness(DoubleVector arg0) {
    DoubleVector ret = new DoubleVector(pagmoPINVOKE.inventory_fitness(swigCPtr, DoubleVector.getCPtr(arg0)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PairOfDoubleVectors get_bounds() {
    PairOfDoubleVectors ret = new PairOfDoubleVectors(pagmoPINVOKE.inventory_get_bounds(swigCPtr), true);
    return ret;
  }

  public void set_seed(uint seed) {
    pagmoPINVOKE.inventory_set_seed(swigCPtr, seed);
  }

  public string get_name() {
    string ret = pagmoPINVOKE.inventory_get_name(swigCPtr);
    return ret;
  }

  public string get_extra_info() {
    string ret = pagmoPINVOKE.inventory_get_extra_info(swigCPtr);
    return ret;
  }

  public uint get_nic() {
    uint ret = pagmoPINVOKE.inventory_get_nic(swigCPtr);
    return ret;
  }

  public uint get_nec() {
    uint ret = pagmoPINVOKE.inventory_get_nec(swigCPtr);
    return ret;
  }

  public uint get_nix() {
    uint ret = pagmoPINVOKE.inventory_get_nix(swigCPtr);
    return ret;
  }

  public uint get_nobj() {
    uint ret = pagmoPINVOKE.inventory_get_nobj(swigCPtr);
    return ret;
  }

  public bool has_batch_fitness() {
    bool ret = pagmoPINVOKE.inventory_has_batch_fitness(swigCPtr);
    return ret;
  }

  public thread_safety get_thread_safety() {
    thread_safety ret = (thread_safety)pagmoPINVOKE.inventory_get_thread_safety(swigCPtr);
    return ret;
  }

}

}
