//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public partial class ipopt : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ipopt(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ipopt obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ipopt obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ipopt() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pagmoPINVOKE.delete_ipopt(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public population evolve(population arg0) {
    population ret = new population(pagmoPINVOKE.ipopt_evolve(swigCPtr, population.getCPtr(arg0)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Ipopt__ApplicationReturnStatus get_last_opt_result() {
    SWIGTYPE_p_Ipopt__ApplicationReturnStatus ret = new SWIGTYPE_p_Ipopt__ApplicationReturnStatus(pagmoPINVOKE.ipopt_get_last_opt_result(swigCPtr), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string get_name() {
    string ret = pagmoPINVOKE.ipopt_get_name(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string get_extra_info() {
    string ret = pagmoPINVOKE.ipopt_get_extra_info(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_verbosity(uint n) {
    pagmoPINVOKE.ipopt_set_verbosity(swigCPtr, n);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_string_option(string arg0, string arg1) {
    pagmoPINVOKE.ipopt_set_string_option(swigCPtr, arg0, arg1);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_integer_option(string arg0, SWIGTYPE_p_Ipopt__Index arg1) {
    pagmoPINVOKE.ipopt_set_integer_option(swigCPtr, arg0, SWIGTYPE_p_Ipopt__Index.getCPtr(arg1));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_numeric_option(string arg0, double arg1) {
    pagmoPINVOKE.ipopt_set_numeric_option(swigCPtr, arg0, arg1);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_string_options(SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t arg0) {
    pagmoPINVOKE.ipopt_set_string_options(swigCPtr, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(arg0));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_integer_options(SWIGTYPE_p_std__mapT_std__string_Ipopt__Index_std__lessT_std__string_t_t arg0) {
    pagmoPINVOKE.ipopt_set_integer_options(swigCPtr, SWIGTYPE_p_std__mapT_std__string_Ipopt__Index_std__lessT_std__string_t_t.getCPtr(arg0));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_numeric_options(SWIGTYPE_p_std__mapT_std__string_double_std__lessT_std__string_t_t arg0) {
    pagmoPINVOKE.ipopt_set_numeric_options(swigCPtr, SWIGTYPE_p_std__mapT_std__string_double_std__lessT_std__string_t_t.getCPtr(arg0));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t get_string_options() {
    SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t ret = new SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t(pagmoPINVOKE.ipopt_get_string_options(swigCPtr), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__mapT_std__string_Ipopt__Index_std__lessT_std__string_t_t get_integer_options() {
    SWIGTYPE_p_std__mapT_std__string_Ipopt__Index_std__lessT_std__string_t_t ret = new SWIGTYPE_p_std__mapT_std__string_Ipopt__Index_std__lessT_std__string_t_t(pagmoPINVOKE.ipopt_get_integer_options(swigCPtr), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__mapT_std__string_double_std__lessT_std__string_t_t get_numeric_options() {
    SWIGTYPE_p_std__mapT_std__string_double_std__lessT_std__string_t_t ret = new SWIGTYPE_p_std__mapT_std__string_double_std__lessT_std__string_t_t(pagmoPINVOKE.ipopt_get_numeric_options(swigCPtr), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void reset_string_options() {
    pagmoPINVOKE.ipopt_reset_string_options(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset_integer_options() {
    pagmoPINVOKE.ipopt_reset_integer_options(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset_numeric_options() {
    pagmoPINVOKE.ipopt_reset_numeric_options(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public thread_safety get_thread_safety() {
    thread_safety ret = (thread_safety)pagmoPINVOKE.ipopt_get_thread_safety(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IpoptLogEntryVector get_log_entries() {
    IpoptLogEntryVector ret = new IpoptLogEntryVector(pagmoPINVOKE.ipopt_get_log_entries(swigCPtr), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public algorithm to_algorithm() {
    algorithm ret = new algorithm(pagmoPINVOKE.ipopt_to_algorithm(swigCPtr), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ipopt() : this(pagmoPINVOKE.new_ipopt(), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
