//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public partial class maco : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal maco(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(maco obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(maco obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~maco() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pagmoPINVOKE.delete_maco(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public maco(uint gen, uint ker, double q, uint threshold, uint n_gen_mark, uint evalstop, double focus, bool memory, uint seed) : this(pagmoPINVOKE.new_maco__SWIG_0(gen, ker, q, threshold, n_gen_mark, evalstop, focus, memory, seed), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public maco(uint gen, uint ker, double q, uint threshold, uint n_gen_mark, uint evalstop, double focus, bool memory) : this(pagmoPINVOKE.new_maco__SWIG_1(gen, ker, q, threshold, n_gen_mark, evalstop, focus, memory), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public maco(uint gen, uint ker, double q, uint threshold, uint n_gen_mark, uint evalstop, double focus) : this(pagmoPINVOKE.new_maco__SWIG_2(gen, ker, q, threshold, n_gen_mark, evalstop, focus), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public maco(uint gen, uint ker, double q, uint threshold, uint n_gen_mark, uint evalstop) : this(pagmoPINVOKE.new_maco__SWIG_3(gen, ker, q, threshold, n_gen_mark, evalstop), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public maco(uint gen, uint ker, double q, uint threshold, uint n_gen_mark) : this(pagmoPINVOKE.new_maco__SWIG_4(gen, ker, q, threshold, n_gen_mark), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public maco(uint gen, uint ker, double q, uint threshold) : this(pagmoPINVOKE.new_maco__SWIG_5(gen, ker, q, threshold), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public maco(uint gen, uint ker, double q) : this(pagmoPINVOKE.new_maco__SWIG_6(gen, ker, q), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public maco(uint gen, uint ker) : this(pagmoPINVOKE.new_maco__SWIG_7(gen, ker), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public maco(uint gen) : this(pagmoPINVOKE.new_maco__SWIG_8(gen), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public maco() : this(pagmoPINVOKE.new_maco__SWIG_9(), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public population evolve(population arg0) {
    population ret = new population(pagmoPINVOKE.maco_evolve(swigCPtr, population.getCPtr(arg0)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_seed(uint arg0) {
    pagmoPINVOKE.maco_set_seed(swigCPtr, arg0);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint get_seed() {
    uint ret = pagmoPINVOKE.maco_get_seed(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_verbosity(uint level) {
    pagmoPINVOKE.maco_set_verbosity(swigCPtr, level);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint get_verbosity() {
    uint ret = pagmoPINVOKE.maco_get_verbosity(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint get_gen() {
    uint ret = pagmoPINVOKE.maco_get_gen(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_bfe(bfe b) {
    pagmoPINVOKE.maco_set_bfe(swigCPtr, bfe.getCPtr(b));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_name() {
    string ret = pagmoPINVOKE.maco_get_name(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string get_extra_info() {
    string ret = pagmoPINVOKE.maco_get_extra_info(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MoVectorLogEntryVector get_log_entries() {
    MoVectorLogEntryVector ret = new MoVectorLogEntryVector(pagmoPINVOKE.maco_get_log_entries(swigCPtr), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public algorithm to_algorithm() {
    algorithm ret = new algorithm(pagmoPINVOKE.maco_to_algorithm(swigCPtr), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
