//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public class MigrationEntry : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MigrationEntry(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MigrationEntry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MigrationEntry obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MigrationEntry() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pagmoPINVOKE.delete_MigrationEntry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double t {
    set {
      pagmoPINVOKE.MigrationEntry_t_set(swigCPtr, value);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = pagmoPINVOKE.MigrationEntry_t_get(swigCPtr);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ulong island_id {
    set {
      pagmoPINVOKE.MigrationEntry_island_id_set(swigCPtr, value);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ulong ret = pagmoPINVOKE.MigrationEntry_island_id_get(swigCPtr);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public DoubleVector x {
    set {
      pagmoPINVOKE.MigrationEntry_x_set(swigCPtr, DoubleVector.getCPtr(value));
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      DoubleVector ret = new DoubleVector(pagmoPINVOKE.MigrationEntry_x_get(swigCPtr), false);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public DoubleVector f {
    set {
      pagmoPINVOKE.MigrationEntry_f_set(swigCPtr, DoubleVector.getCPtr(value));
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      DoubleVector ret = new DoubleVector(pagmoPINVOKE.MigrationEntry_f_get(swigCPtr), false);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__size_t migration_id {
    set {
      pagmoPINVOKE.MigrationEntry_migration_id_set(swigCPtr, SWIGTYPE_p_std__size_t.getCPtr(value));
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__size_t ret = new SWIGTYPE_p_std__size_t(pagmoPINVOKE.MigrationEntry_migration_id_get(swigCPtr), true);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__size_t immigrant_id {
    set {
      pagmoPINVOKE.MigrationEntry_immigrant_id_set(swigCPtr, SWIGTYPE_p_std__size_t.getCPtr(value));
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__size_t ret = new SWIGTYPE_p_std__size_t(pagmoPINVOKE.MigrationEntry_immigrant_id_get(swigCPtr), true);
      if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public MigrationEntry() : this(pagmoPINVOKE.new_MigrationEntry__SWIG_0(), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public MigrationEntry(double t_, ulong island_id_, DoubleVector x_, DoubleVector f_, SWIGTYPE_p_std__size_t migration_id_, SWIGTYPE_p_std__size_t immigrant_id_) : this(pagmoPINVOKE.new_MigrationEntry__SWIG_1(t_, island_id_, DoubleVector.getCPtr(x_), DoubleVector.getCPtr(f_), SWIGTYPE_p_std__size_t.getCPtr(migration_id_), SWIGTYPE_p_std__size_t.getCPtr(immigrant_id_)), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
