//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public partial class pagmo {
  public static PsoLogEntryVector Pso_GetLogEntries(pso algo) {
    PsoLogEntryVector ret = new PsoLogEntryVector(pagmoPINVOKE.Pso_GetLogEntries(pso.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static PsoLogEntryVector PsoGen_GetLogEntries(pso_gen algo) {
    PsoLogEntryVector ret = new PsoLogEntryVector(pagmoPINVOKE.PsoGen_GetLogEntries(pso_gen.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static XnesLogEntryVector Xnes_GetLogEntries(xnes algo) {
    XnesLogEntryVector ret = new XnesLogEntryVector(pagmoPINVOKE.Xnes_GetLogEntries(xnes.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static MoVectorLogEntryVector Maco_GetLogEntries(maco algo) {
    MoVectorLogEntryVector ret = new MoVectorLogEntryVector(pagmoPINVOKE.Maco_GetLogEntries(maco.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static MoeadLogEntryVector Moead_GetLogEntries(moead algo) {
    MoeadLogEntryVector ret = new MoeadLogEntryVector(pagmoPINVOKE.Moead_GetLogEntries(moead.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static MoeadLogEntryVector MoeadGen_GetLogEntries(moead_gen algo) {
    MoeadLogEntryVector ret = new MoeadLogEntryVector(pagmoPINVOKE.MoeadGen_GetLogEntries(moead_gen.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static MoVectorLogEntryVector Nsga2_GetLogEntries(nsga2 algo) {
    MoVectorLogEntryVector ret = new MoVectorLogEntryVector(pagmoPINVOKE.Nsga2_GetLogEntries(nsga2.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static MoVectorLogEntryVector Nspso_GetLogEntries(nspso algo) {
    MoVectorLogEntryVector ret = new MoVectorLogEntryVector(pagmoPINVOKE.Nspso_GetLogEntries(nspso.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static GwoLogEntryVector Gwo_GetLogEntries(gwo algo) {
    GwoLogEntryVector ret = new GwoLogEntryVector(pagmoPINVOKE.Gwo_GetLogEntries(gwo.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static De1220LogEntryVector De1220_GetLogEntries(de1220 algo) {
    De1220LogEntryVector ret = new De1220LogEntryVector(pagmoPINVOKE.De1220_GetLogEntries(de1220.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static CompassSearchLogEntryVector CompassSearch_GetLogEntries(compass_search algo) {
    CompassSearchLogEntryVector ret = new CompassSearchLogEntryVector(pagmoPINVOKE.CompassSearch_GetLogEntries(compass_search.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static NloptLogEntryVector Nlopt_GetLogEntries(nlopt algo) {
    NloptLogEntryVector ret = new NloptLogEntryVector(pagmoPINVOKE.Nlopt_GetLogEntries(nlopt.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SimulatedAnnealingLogEntryVector SimulatedAnnealing_GetLogEntries(simulated_annealing algo) {
    SimulatedAnnealingLogEntryVector ret = new SimulatedAnnealingLogEntryVector(pagmoPINVOKE.SimulatedAnnealing_GetLogEntries(simulated_annealing.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SgaLogEntryVector Sga_GetLogEntries(sga algo) {
    SgaLogEntryVector ret = new SgaLogEntryVector(pagmoPINVOKE.Sga_GetLogEntries(sga.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SadeLogEntryVector Sade_GetLogEntries(sade algo) {
    SadeLogEntryVector ret = new SadeLogEntryVector(pagmoPINVOKE.Sade_GetLogEntries(sade.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SeaLogEntryVector Sea_GetLogEntries(sea algo) {
    SeaLogEntryVector ret = new SeaLogEntryVector(pagmoPINVOKE.Sea_GetLogEntries(sea.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static CmaesLogEntryVector Cmaes_GetLogEntries(cmaes algo) {
    CmaesLogEntryVector ret = new CmaesLogEntryVector(pagmoPINVOKE.Cmaes_GetLogEntries(cmaes.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static CstrsLogEntryVector Cstrs_GetLogEntries(cstrs_self_adaptive algo) {
    CstrsLogEntryVector ret = new CstrsLogEntryVector(pagmoPINVOKE.Cstrs_GetLogEntries(cstrs_self_adaptive.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DeLogEntryVector De_GetLogEntries(de algo) {
    DeLogEntryVector ret = new DeLogEntryVector(pagmoPINVOKE.De_GetLogEntries(de.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static IhsLogEntryVector Ihs_GetLogEntries(ihs algo) {
    IhsLogEntryVector ret = new IhsLogEntryVector(pagmoPINVOKE.Ihs_GetLogEntries(ihs.getCPtr(algo)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static FNDSResult FastNonDominatedSorting(VectorOfVectorOfDoubles input) {
    FNDSResult ret = new FNDSResult(pagmoPINVOKE.FastNonDominatedSorting(VectorOfVectorOfDoubles.getCPtr(input)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint max_stream_output_length() {
    uint ret = pagmoPINVOKE.max_stream_output_length();
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool pareto_dominance(DoubleVector arg0, DoubleVector arg1) {
    bool ret = pagmoPINVOKE.pareto_dominance(DoubleVector.getCPtr(arg0), DoubleVector.getCPtr(arg1));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ULongLongVector non_dominated_front_2d(VectorOfVectorOfDoubles arg0) {
    ULongLongVector ret = new ULongLongVector(pagmoPINVOKE.non_dominated_front_2d(VectorOfVectorOfDoubles.getCPtr(arg0)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DoubleVector crowding_distance(VectorOfVectorOfDoubles arg0) {
    DoubleVector ret = new DoubleVector(pagmoPINVOKE.crowding_distance(VectorOfVectorOfDoubles.getCPtr(arg0)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ULongLongVector sort_population_mo(VectorOfVectorOfDoubles arg0) {
    ULongLongVector ret = new ULongLongVector(pagmoPINVOKE.sort_population_mo(VectorOfVectorOfDoubles.getCPtr(arg0)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ULongLongVector select_best_N_mo(VectorOfVectorOfDoubles arg0, ulong arg1) {
    ULongLongVector ret = new ULongLongVector(pagmoPINVOKE.select_best_N_mo(VectorOfVectorOfDoubles.getCPtr(arg0), arg1), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DoubleVector ideal(VectorOfVectorOfDoubles arg0) {
    DoubleVector ret = new DoubleVector(pagmoPINVOKE.ideal(VectorOfVectorOfDoubles.getCPtr(arg0)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DoubleVector nadir(VectorOfVectorOfDoubles arg0) {
    DoubleVector ret = new DoubleVector(pagmoPINVOKE.nadir(VectorOfVectorOfDoubles.getCPtr(arg0)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DoubleVector decompose_objectives(DoubleVector arg0, DoubleVector arg1, DoubleVector arg2, string arg3) {
    DoubleVector ret = new DoubleVector(pagmoPINVOKE.decompose_objectives(DoubleVector.getCPtr(arg0), DoubleVector.getCPtr(arg1), DoubleVector.getCPtr(arg2), arg3), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static readonly string PAGMO_VERSION = pagmoPINVOKE.PAGMO_VERSION_get();
  public static readonly int PAGMO_VERSION_MAJOR = pagmoPINVOKE.PAGMO_VERSION_MAJOR_get();
  public static readonly int PAGMO_VERSION_MINOR = pagmoPINVOKE.PAGMO_VERSION_MINOR_get();
  public static readonly int PAGMO_VERSION_PATCH = pagmoPINVOKE.PAGMO_VERSION_PATCH_get();
}

}
