//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public partial class ProblemCallback : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ProblemCallback(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ProblemCallback obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ProblemCallback obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ProblemCallback() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pagmoPINVOKE.delete_ProblemCallback(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual DoubleVector fitness(DoubleVector x) {
    DoubleVector ret = new DoubleVector(pagmoPINVOKE.ProblemCallback_fitness(swigCPtr, DoubleVector.getCPtr(x)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual PairOfDoubleVectors get_bounds() {
    PairOfDoubleVectors ret = new PairOfDoubleVectors(pagmoPINVOKE.ProblemCallback_get_bounds(swigCPtr), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string get_name() {
    string ret = (SwigDerivedClassHasMethod("get_name", swigMethodTypes2) ? pagmoPINVOKE.ProblemCallback_get_nameSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_get_name(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string get_extra_info() {
    string ret = (SwigDerivedClassHasMethod("get_extra_info", swigMethodTypes3) ? pagmoPINVOKE.ProblemCallback_get_extra_infoSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_get_extra_info(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint get_nobj() {
    uint ret = (SwigDerivedClassHasMethod("get_nobj", swigMethodTypes4) ? pagmoPINVOKE.ProblemCallback_get_nobjSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_get_nobj(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint get_nec() {
    uint ret = (SwigDerivedClassHasMethod("get_nec", swigMethodTypes5) ? pagmoPINVOKE.ProblemCallback_get_necSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_get_nec(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint get_nic() {
    uint ret = (SwigDerivedClassHasMethod("get_nic", swigMethodTypes6) ? pagmoPINVOKE.ProblemCallback_get_nicSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_get_nic(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint get_nix() {
    uint ret = (SwigDerivedClassHasMethod("get_nix", swigMethodTypes7) ? pagmoPINVOKE.ProblemCallback_get_nixSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_get_nix(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DoubleVector batch_fitness(DoubleVector arg0) {
    DoubleVector ret = new DoubleVector((SwigDerivedClassHasMethod("batch_fitness", swigMethodTypes8) ? pagmoPINVOKE.ProblemCallback_batch_fitnessSwigExplicitProblemCallback(swigCPtr, DoubleVector.getCPtr(arg0)) : pagmoPINVOKE.ProblemCallback_batch_fitness(swigCPtr, DoubleVector.getCPtr(arg0))), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool has_batch_fitness() {
    bool ret = (SwigDerivedClassHasMethod("has_batch_fitness", swigMethodTypes9) ? pagmoPINVOKE.ProblemCallback_has_batch_fitnessSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_has_batch_fitness(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DoubleVector gradient(DoubleVector arg0) {
    DoubleVector ret = new DoubleVector((SwigDerivedClassHasMethod("gradient", swigMethodTypes10) ? pagmoPINVOKE.ProblemCallback_gradientSwigExplicitProblemCallback(swigCPtr, DoubleVector.getCPtr(arg0)) : pagmoPINVOKE.ProblemCallback_gradient(swigCPtr, DoubleVector.getCPtr(arg0))), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool has_gradient() {
    bool ret = (SwigDerivedClassHasMethod("has_gradient", swigMethodTypes11) ? pagmoPINVOKE.ProblemCallback_has_gradientSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_has_gradient(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual SWIGTYPE_p_std__vectorT_std__pairT_size_t_size_t_t_t gradient_sparsity() {
    SWIGTYPE_p_std__vectorT_std__pairT_size_t_size_t_t_t ret = new SWIGTYPE_p_std__vectorT_std__pairT_size_t_size_t_t_t((SwigDerivedClassHasMethod("gradient_sparsity", swigMethodTypes12) ? pagmoPINVOKE.ProblemCallback_gradient_sparsitySwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_gradient_sparsity(swigCPtr)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool has_gradient_sparsity() {
    bool ret = (SwigDerivedClassHasMethod("has_gradient_sparsity", swigMethodTypes13) ? pagmoPINVOKE.ProblemCallback_has_gradient_sparsitySwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_has_gradient_sparsity(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual VectorOfVectorOfDoubles hessians(DoubleVector arg0) {
    VectorOfVectorOfDoubles ret = new VectorOfVectorOfDoubles((SwigDerivedClassHasMethod("hessians", swigMethodTypes14) ? pagmoPINVOKE.ProblemCallback_hessiansSwigExplicitProblemCallback(swigCPtr, DoubleVector.getCPtr(arg0)) : pagmoPINVOKE.ProblemCallback_hessians(swigCPtr, DoubleVector.getCPtr(arg0))), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool has_hessians() {
    bool ret = (SwigDerivedClassHasMethod("has_hessians", swigMethodTypes15) ? pagmoPINVOKE.ProblemCallback_has_hessiansSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_has_hessians(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual SWIGTYPE_p_std__vectorT_std__vectorT_std__pairT_size_t_size_t_t_t_t hessians_sparsity() {
    SWIGTYPE_p_std__vectorT_std__vectorT_std__pairT_size_t_size_t_t_t_t ret = new SWIGTYPE_p_std__vectorT_std__vectorT_std__pairT_size_t_size_t_t_t_t((SwigDerivedClassHasMethod("hessians_sparsity", swigMethodTypes16) ? pagmoPINVOKE.ProblemCallback_hessians_sparsitySwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_hessians_sparsity(swigCPtr)), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool has_hessians_sparsity() {
    bool ret = (SwigDerivedClassHasMethod("has_hessians_sparsity", swigMethodTypes17) ? pagmoPINVOKE.ProblemCallback_has_hessians_sparsitySwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_has_hessians_sparsity(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void set_seed(uint arg0) {
    if (SwigDerivedClassHasMethod("set_seed", swigMethodTypes18)) pagmoPINVOKE.ProblemCallback_set_seedSwigExplicitProblemCallback(swigCPtr, arg0); else pagmoPINVOKE.ProblemCallback_set_seed(swigCPtr, arg0);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool has_set_seed() {
    bool ret = (SwigDerivedClassHasMethod("has_set_seed", swigMethodTypes19) ? pagmoPINVOKE.ProblemCallback_has_set_seedSwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_has_set_seed(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual ThreadSafety get_thread_safety() {
    ThreadSafety ret = (ThreadSafety)(SwigDerivedClassHasMethod("get_thread_safety", swigMethodTypes20) ? pagmoPINVOKE.ProblemCallback_get_thread_safetySwigExplicitProblemCallback(swigCPtr) : pagmoPINVOKE.ProblemCallback_get_thread_safety(swigCPtr));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ProblemCallback() : this(pagmoPINVOKE.new_ProblemCallback(), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("fitness", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateProblemCallback_0(SwigDirectorMethodfitness);
    if (SwigDerivedClassHasMethod("get_bounds", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateProblemCallback_1(SwigDirectorMethodget_bounds);
    if (SwigDerivedClassHasMethod("get_name", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateProblemCallback_2(SwigDirectorMethodget_name);
    if (SwigDerivedClassHasMethod("get_extra_info", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateProblemCallback_3(SwigDirectorMethodget_extra_info);
    if (SwigDerivedClassHasMethod("get_nobj", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateProblemCallback_4(SwigDirectorMethodget_nobj);
    if (SwigDerivedClassHasMethod("get_nec", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateProblemCallback_5(SwigDirectorMethodget_nec);
    if (SwigDerivedClassHasMethod("get_nic", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateProblemCallback_6(SwigDirectorMethodget_nic);
    if (SwigDerivedClassHasMethod("get_nix", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateProblemCallback_7(SwigDirectorMethodget_nix);
    if (SwigDerivedClassHasMethod("batch_fitness", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateProblemCallback_8(SwigDirectorMethodbatch_fitness);
    if (SwigDerivedClassHasMethod("has_batch_fitness", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateProblemCallback_9(SwigDirectorMethodhas_batch_fitness);
    if (SwigDerivedClassHasMethod("gradient", swigMethodTypes10))
      swigDelegate10 = new SwigDelegateProblemCallback_10(SwigDirectorMethodgradient);
    if (SwigDerivedClassHasMethod("has_gradient", swigMethodTypes11))
      swigDelegate11 = new SwigDelegateProblemCallback_11(SwigDirectorMethodhas_gradient);
    if (SwigDerivedClassHasMethod("gradient_sparsity", swigMethodTypes12))
      swigDelegate12 = new SwigDelegateProblemCallback_12(SwigDirectorMethodgradient_sparsity);
    if (SwigDerivedClassHasMethod("has_gradient_sparsity", swigMethodTypes13))
      swigDelegate13 = new SwigDelegateProblemCallback_13(SwigDirectorMethodhas_gradient_sparsity);
    if (SwigDerivedClassHasMethod("hessians", swigMethodTypes14))
      swigDelegate14 = new SwigDelegateProblemCallback_14(SwigDirectorMethodhessians);
    if (SwigDerivedClassHasMethod("has_hessians", swigMethodTypes15))
      swigDelegate15 = new SwigDelegateProblemCallback_15(SwigDirectorMethodhas_hessians);
    if (SwigDerivedClassHasMethod("hessians_sparsity", swigMethodTypes16))
      swigDelegate16 = new SwigDelegateProblemCallback_16(SwigDirectorMethodhessians_sparsity);
    if (SwigDerivedClassHasMethod("has_hessians_sparsity", swigMethodTypes17))
      swigDelegate17 = new SwigDelegateProblemCallback_17(SwigDirectorMethodhas_hessians_sparsity);
    if (SwigDerivedClassHasMethod("set_seed", swigMethodTypes18))
      swigDelegate18 = new SwigDelegateProblemCallback_18(SwigDirectorMethodset_seed);
    if (SwigDerivedClassHasMethod("has_set_seed", swigMethodTypes19))
      swigDelegate19 = new SwigDelegateProblemCallback_19(SwigDirectorMethodhas_set_seed);
    if (SwigDerivedClassHasMethod("get_thread_safety", swigMethodTypes20))
      swigDelegate20 = new SwigDelegateProblemCallback_20(SwigDirectorMethodget_thread_safety);
    pagmoPINVOKE.ProblemCallback_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9, swigDelegate10, swigDelegate11, swigDelegate12, swigDelegate13, swigDelegate14, swigDelegate15, swigDelegate16, swigDelegate17, swigDelegate18, swigDelegate19, swigDelegate20);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(ProblemCallback))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private global::System.IntPtr SwigDirectorMethodfitness(global::System.IntPtr x) {
    return DoubleVector.getCPtr(fitness(new DoubleVector(x, false))).Handle;
  }

  private global::System.IntPtr SwigDirectorMethodget_bounds() {
    return PairOfDoubleVectors.getCPtr(get_bounds()).Handle;
  }

  private string SwigDirectorMethodget_name() {
    return 
    ((global::System.Func<string>)(() => {
      try { return get_name(); }
      catch (global::System.Exception _exSwigDirector) {
        pagmoPINVOKE.SWIGPendingException.Set(_exSwigDirector);
        return null;
      }
    }))()
;
  }

  private string SwigDirectorMethodget_extra_info() {
    return 
    ((global::System.Func<string>)(() => {
      try { return get_extra_info(); }
      catch (global::System.Exception _exSwigDirector) {
        pagmoPINVOKE.SWIGPendingException.Set(_exSwigDirector);
        return null;
      }
    }))()
;
  }

  private uint SwigDirectorMethodget_nobj() {
    return get_nobj();
  }

  private uint SwigDirectorMethodget_nec() {
    return get_nec();
  }

  private uint SwigDirectorMethodget_nic() {
    return get_nic();
  }

  private uint SwigDirectorMethodget_nix() {
    return get_nix();
  }

  private global::System.IntPtr SwigDirectorMethodbatch_fitness(global::System.IntPtr arg0) {
    return DoubleVector.getCPtr(batch_fitness(new DoubleVector(arg0, false))).Handle;
  }

  private bool SwigDirectorMethodhas_batch_fitness() {
    return 
    ((global::System.Func<bool>)(() => {
      try { return has_batch_fitness(); }
      catch (global::System.Exception _exSwigDirector) {
        pagmoPINVOKE.SWIGPendingException.Set(_exSwigDirector);
        return false;
      }
    }))()
;
  }

  private global::System.IntPtr SwigDirectorMethodgradient(global::System.IntPtr arg0) {
    return DoubleVector.getCPtr(gradient(new DoubleVector(arg0, false))).Handle;
  }

  private bool SwigDirectorMethodhas_gradient() {
    return 
    ((global::System.Func<bool>)(() => {
      try { return has_gradient(); }
      catch (global::System.Exception _exSwigDirector) {
        pagmoPINVOKE.SWIGPendingException.Set(_exSwigDirector);
        return false;
      }
    }))()
;
  }

  private global::System.IntPtr SwigDirectorMethodgradient_sparsity() {
    return SWIGTYPE_p_std__vectorT_std__pairT_size_t_size_t_t_t.getCPtr(gradient_sparsity()).Handle;
  }

  private bool SwigDirectorMethodhas_gradient_sparsity() {
    return 
    ((global::System.Func<bool>)(() => {
      try { return has_gradient_sparsity(); }
      catch (global::System.Exception _exSwigDirector) {
        pagmoPINVOKE.SWIGPendingException.Set(_exSwigDirector);
        return false;
      }
    }))()
;
  }

  private global::System.IntPtr SwigDirectorMethodhessians(global::System.IntPtr arg0) {
    return VectorOfVectorOfDoubles.getCPtr(hessians(new DoubleVector(arg0, false))).Handle;
  }

  private bool SwigDirectorMethodhas_hessians() {
    return 
    ((global::System.Func<bool>)(() => {
      try { return has_hessians(); }
      catch (global::System.Exception _exSwigDirector) {
        pagmoPINVOKE.SWIGPendingException.Set(_exSwigDirector);
        return false;
      }
    }))()
;
  }

  private global::System.IntPtr SwigDirectorMethodhessians_sparsity() {
    return SWIGTYPE_p_std__vectorT_std__vectorT_std__pairT_size_t_size_t_t_t_t.getCPtr(hessians_sparsity()).Handle;
  }

  private bool SwigDirectorMethodhas_hessians_sparsity() {
    return 
    ((global::System.Func<bool>)(() => {
      try { return has_hessians_sparsity(); }
      catch (global::System.Exception _exSwigDirector) {
        pagmoPINVOKE.SWIGPendingException.Set(_exSwigDirector);
        return false;
      }
    }))()
;
  }

  private void SwigDirectorMethodset_seed(uint arg0) {
    
    try {
      set_seed(arg0);
    } catch (global::System.Exception _exSwigDirector) {
      pagmoPINVOKE.SWIGPendingException.Set(_exSwigDirector);
    }
;
  }

  private bool SwigDirectorMethodhas_set_seed() {
    return 
    ((global::System.Func<bool>)(() => {
      try { return has_set_seed(); }
      catch (global::System.Exception _exSwigDirector) {
        pagmoPINVOKE.SWIGPendingException.Set(_exSwigDirector);
        return false;
      }
    }))()
;
  }

  private int SwigDirectorMethodget_thread_safety() {
    return (int)get_thread_safety();
  }

  public delegate global::System.IntPtr SwigDelegateProblemCallback_0(global::System.IntPtr x);
  public delegate global::System.IntPtr SwigDelegateProblemCallback_1();
  public delegate string SwigDelegateProblemCallback_2();
  public delegate string SwigDelegateProblemCallback_3();
  public delegate uint SwigDelegateProblemCallback_4();
  public delegate uint SwigDelegateProblemCallback_5();
  public delegate uint SwigDelegateProblemCallback_6();
  public delegate uint SwigDelegateProblemCallback_7();
  public delegate global::System.IntPtr SwigDelegateProblemCallback_8(global::System.IntPtr arg0);
  public delegate bool SwigDelegateProblemCallback_9();
  public delegate global::System.IntPtr SwigDelegateProblemCallback_10(global::System.IntPtr arg0);
  public delegate bool SwigDelegateProblemCallback_11();
  public delegate global::System.IntPtr SwigDelegateProblemCallback_12();
  public delegate bool SwigDelegateProblemCallback_13();
  public delegate global::System.IntPtr SwigDelegateProblemCallback_14(global::System.IntPtr arg0);
  public delegate bool SwigDelegateProblemCallback_15();
  public delegate global::System.IntPtr SwigDelegateProblemCallback_16();
  public delegate bool SwigDelegateProblemCallback_17();
  public delegate void SwigDelegateProblemCallback_18(uint arg0);
  public delegate bool SwigDelegateProblemCallback_19();
  public delegate int SwigDelegateProblemCallback_20();

  private SwigDelegateProblemCallback_0 swigDelegate0;
  private SwigDelegateProblemCallback_1 swigDelegate1;
  private SwigDelegateProblemCallback_2 swigDelegate2;
  private SwigDelegateProblemCallback_3 swigDelegate3;
  private SwigDelegateProblemCallback_4 swigDelegate4;
  private SwigDelegateProblemCallback_5 swigDelegate5;
  private SwigDelegateProblemCallback_6 swigDelegate6;
  private SwigDelegateProblemCallback_7 swigDelegate7;
  private SwigDelegateProblemCallback_8 swigDelegate8;
  private SwigDelegateProblemCallback_9 swigDelegate9;
  private SwigDelegateProblemCallback_10 swigDelegate10;
  private SwigDelegateProblemCallback_11 swigDelegate11;
  private SwigDelegateProblemCallback_12 swigDelegate12;
  private SwigDelegateProblemCallback_13 swigDelegate13;
  private SwigDelegateProblemCallback_14 swigDelegate14;
  private SwigDelegateProblemCallback_15 swigDelegate15;
  private SwigDelegateProblemCallback_16 swigDelegate16;
  private SwigDelegateProblemCallback_17 swigDelegate17;
  private SwigDelegateProblemCallback_18 swigDelegate18;
  private SwigDelegateProblemCallback_19 swigDelegate19;
  private SwigDelegateProblemCallback_20 swigDelegate20;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(DoubleVector) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes6 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes7 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes8 = new global::System.Type[] { typeof(DoubleVector) };
  private static global::System.Type[] swigMethodTypes9 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes10 = new global::System.Type[] { typeof(DoubleVector) };
  private static global::System.Type[] swigMethodTypes11 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes12 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes13 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes14 = new global::System.Type[] { typeof(DoubleVector) };
  private static global::System.Type[] swigMethodTypes15 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes16 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes17 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes18 = new global::System.Type[] { typeof(uint) };
  private static global::System.Type[] swigMethodTypes19 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes20 = new global::System.Type[] {  };
}

}
