//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pagmo {

public class VectorOfVectorIndexes : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<ULongLongVector>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorOfVectorIndexes(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorOfVectorIndexes obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorOfVectorIndexes obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorOfVectorIndexes() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pagmoPINVOKE.delete_VectorOfVectorIndexes(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorOfVectorIndexes(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ULongLongVector element in c) {
      this.Add(element);
    }
  }

  public VectorOfVectorIndexes(global::System.Collections.Generic.IEnumerable<ULongLongVector> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ULongLongVector element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public ULongLongVector this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(ULongLongVector[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(ULongLongVector[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, ULongLongVector[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public ULongLongVector[] ToArray() {
    ULongLongVector[] array = new ULongLongVector[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<ULongLongVector> global::System.Collections.Generic.IEnumerable<ULongLongVector>.GetEnumerator() {
    return new VectorOfVectorIndexesEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorOfVectorIndexesEnumerator(this);
  }

  public VectorOfVectorIndexesEnumerator GetEnumerator() {
    return new VectorOfVectorIndexesEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorOfVectorIndexesEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<ULongLongVector>
  {
    private VectorOfVectorIndexes collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorOfVectorIndexesEnumerator(VectorOfVectorIndexes collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public ULongLongVector Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (ULongLongVector)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorOfVectorIndexes() : this(pagmoPINVOKE.new_VectorOfVectorIndexes__SWIG_0(), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorOfVectorIndexes(VectorOfVectorIndexes other) : this(pagmoPINVOKE.new_VectorOfVectorIndexes__SWIG_1(VectorOfVectorIndexes.getCPtr(other)), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    pagmoPINVOKE.VectorOfVectorIndexes_Clear(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(ULongLongVector x) {
    pagmoPINVOKE.VectorOfVectorIndexes_Add(swigCPtr, ULongLongVector.getCPtr(x));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = pagmoPINVOKE.VectorOfVectorIndexes_size(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool empty() {
    bool ret = pagmoPINVOKE.VectorOfVectorIndexes_empty(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = pagmoPINVOKE.VectorOfVectorIndexes_capacity(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    pagmoPINVOKE.VectorOfVectorIndexes_reserve(swigCPtr, n);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorOfVectorIndexes(int capacity) : this(pagmoPINVOKE.new_VectorOfVectorIndexes__SWIG_2(capacity), true) {
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  private ULongLongVector getitemcopy(int index) {
    ULongLongVector ret = new ULongLongVector(pagmoPINVOKE.VectorOfVectorIndexes_getitemcopy(swigCPtr, index), true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ULongLongVector getitem(int index) {
    ULongLongVector ret = new ULongLongVector(pagmoPINVOKE.VectorOfVectorIndexes_getitem(swigCPtr, index), false);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, ULongLongVector val) {
    pagmoPINVOKE.VectorOfVectorIndexes_setitem(swigCPtr, index, ULongLongVector.getCPtr(val));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorOfVectorIndexes values) {
    pagmoPINVOKE.VectorOfVectorIndexes_AddRange(swigCPtr, VectorOfVectorIndexes.getCPtr(values));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorOfVectorIndexes GetRange(int index, int count) {
    global::System.IntPtr cPtr = pagmoPINVOKE.VectorOfVectorIndexes_GetRange(swigCPtr, index, count);
    VectorOfVectorIndexes ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorOfVectorIndexes(cPtr, true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, ULongLongVector x) {
    pagmoPINVOKE.VectorOfVectorIndexes_Insert(swigCPtr, index, ULongLongVector.getCPtr(x));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorOfVectorIndexes values) {
    pagmoPINVOKE.VectorOfVectorIndexes_InsertRange(swigCPtr, index, VectorOfVectorIndexes.getCPtr(values));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    pagmoPINVOKE.VectorOfVectorIndexes_RemoveAt(swigCPtr, index);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    pagmoPINVOKE.VectorOfVectorIndexes_RemoveRange(swigCPtr, index, count);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorOfVectorIndexes Repeat(ULongLongVector value, int count) {
    global::System.IntPtr cPtr = pagmoPINVOKE.VectorOfVectorIndexes_Repeat(ULongLongVector.getCPtr(value), count);
    VectorOfVectorIndexes ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorOfVectorIndexes(cPtr, true);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    pagmoPINVOKE.VectorOfVectorIndexes_Reverse__SWIG_0(swigCPtr);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    pagmoPINVOKE.VectorOfVectorIndexes_Reverse__SWIG_1(swigCPtr, index, count);
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorOfVectorIndexes values) {
    pagmoPINVOKE.VectorOfVectorIndexes_SetRange(swigCPtr, index, VectorOfVectorIndexes.getCPtr(values));
    if (pagmoPINVOKE.SWIGPendingException.Pending) throw pagmoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
